export default function AboutUs() {
    return (
        <div>
            <h1>About us page </h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Phasellus egestas tellus rutrum tellus pellentesque. Fermentum iaculis eu non diam phasellus. In cursus turpis massa tincidunt dui ut. Odio pellentesque diam volutpat commodo sed. Velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Pulvinar etiam non quam lacus. Phasellus egestas tellus rutrum tellus pellentesque eu. Dictumst quisque sagittis purus sit amet volutpat consequat mauris. Aliquet enim tortor at auctor urna nunc id. Sed enim ut sem viverra aliquet eget sit amet tellus. Sed risus ultricies tristique nulla aliquet enim tortor. Mauris ultrices eros in cursus turpis massa tincidunt dui. Nibh sit amet commodo nulla. Aenean sed adipiscing diam donec adipiscing tristique risus. Mauris vitae ultricies leo integer malesuada nunc vel risus commodo.

Elementum pulvinar etiam non quam lacus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Massa massa ultricies mi quis hendrerit dolor magna eget. Dolor morbi non arcu risus quis varius quam. Morbi tristique senectus et netus et malesuada fames. Augue lacus viverra vitae congue eu consequat ac felis. Odio tempor orci dapibus ultrices in iaculis nunc sed augue. Faucibus ornare suspendisse sed nisi lacus sed. Fusce id velit ut tortor pretium viverra suspendisse. Urna condimentum mattis pellentesque id. Egestas erat imperdiet sed euismod.

Purus faucibus ornare suspendisse sed. Nam libero justo laoreet sit amet cursus sit amet. Praesent tristique magna sit amet. Ultrices in iaculis nunc sed augue lacus. Blandit turpis cursus in hac habitasse. Donec ac odio tempor orci. At lectus urna duis convallis. Quisque non tellus orci ac auctor augue mauris. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Tellus in hac habitasse platea dictumst. Gravida dictum fusce ut placerat orci nulla. Tincidunt augue interdum velit euismod in pellentesque massa placerat duis. Dui nunc mattis enim ut tellus elementum. Etiam dignissim diam quis enim lobortis scelerisque. Pharetra et ultrices neque ornare. Faucibus scelerisque eleifend donec pretium vulputate. Gravida rutrum quisque non tellus orci ac auctor augue mauris. Pellentesque diam volutpat commodo sed egestas egestas. Lorem ipsum dolor sit amet consectetur adipiscing elit.

Arcu bibendum at varius vel. Nibh cras pulvinar mattis nunc sed blandit libero. Facilisis gravida neque convallis a cras semper auctor neque. Pretium lectus quam id leo in vitae turpis massa. Vitae nunc sed velit dignissim sodales ut eu. Eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper. Volutpat sed cras ornare arcu dui vivamus arcu felis. Id eu nisl nunc mi ipsum faucibus vitae. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Elementum nibh tellus molestie nunc non blandit massa enim. Maecenas ultricies mi eget mauris pharetra. Mattis aliquam faucibus purus in massa tempor nec. Mi ipsum faucibus vitae aliquet. Ut aliquam purus sit amet luctus venenatis lectus.

Tristique et egestas quis ipsum suspendisse ultrices gravida dictum fusce. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Blandit massa enim nec dui nunc mattis enim. Nisi est sit amet facilisis magna. Laoreet sit amet cursus sit amet dictum sit amet justo. Convallis aenean et tortor at risus. Semper quis lectus nulla at volutpat diam. Diam maecenas ultricies mi eget mauris. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Augue mauris augue neque gravida. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Pulvinar elementum integer enim neque volutpat ac tincidunt. Eget est lorem ipsum dolor sit amet.</p>

        </div>
    )
}