import Head from 'next/head'

import Main from '../components/main'
export default function Home({ events }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main data={events} />
    </>
  )
}
export async function getServerSideProps() {
  const data = await import('../data/data.json')
  return (
    {
      props: {
        events: data.events_categories
      }
    }
  )
}
